name: Bale Bot v21 Finalllllll

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 355

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install System Dependencies (Audio, Video & ALSA)
        run: |
          sudo apt-get update
          # نصب برنامه‌های مدیریت صدا و ویدیو که ربات شما نیاز دارد
          sudo apt-get install -y ffmpeg pulseaudio alsa-utils kmod
          # تلاش برای فعال کردن کارت صدای مجازی (ممکن است در ماشین مجازی محدود باشد)
          sudo modprobe snd-aloop || echo "Warning: snd-aloop module could not be loaded."

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # اضافه شدن playwright-stealth به لیست نصب
          pip install requests playwright beautifulsoup4 yt-dlp playwright-stealth

      - name: Install Playwright Chromium & Dependencies
        run: |
          python -m playwright install chromium
          python -m playwright install-deps chromium

      - name: Run bot
        env:
          BALE_BOT_TOKEN: ${{ secrets.BALE_BOT_TOKEN }}
        run: |
          # استارت کردن سرویس صدا قبل از اجرای ربات
          pulseaudio --start || true
          python bot.py
          
