name: Yeeeessss

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 355
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install requests playwright beautifulsoup4 playwright-stealth
          python -m playwright install chromium
      - name: Run bot
        env:
          BALE_BOT_TOKEN: ${{ secrets.BALE_BOT_TOKEN }}
        run: python bot.py
